lcn_wysihtml5_demo_create:
    path:     /lcn-wysihtml5/demo
    defaults: { _controller: LcnWYSIHTML5Bundle:Demo:createOrUpdate }

lcn_wysihtml5_demo_edit:
    path:     /lcn-wysihtml5/demo/{id}/edit
    defaults: { _controller: LcnWYSIHTML5Bundle:Demo:createOrUpdate }

lcn_wysihtml5_demo_show:
    path:     /lcn-wysihtml5/demo/{id}
    defaults: { _controller: LcnWYSIHTML5Bundle:Demo:show }